services:
  my_app:
    build:
      context: .  # Build from the current directory
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Map port 5000 on the host to port 5000 in the container
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]  # Enable GPU support
    runtime: nvidia  # Specify NVIDIA runtime for GPU
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  # Make all GPUs available
